#!/bin/bash

which socat >/dev/null || { echo "socat not found"; exit 1; }

local_path=`cd $(dirname $0); pwd`
export WEBLET_HOME=${local_path}/weblet-local/html/weblet.html
export WEBLET_PATH=${local_path}/weblet-local
export LD_LIBRARY_PATH=${local_path}/weblet-local/

is_daemon=
is_debug=

while [ "$1" != "" ]; do
    if [ "$1" = "-d" ]; then
        is_daemon=YES
    fi
    if [ "$1" = "-D" ]; then
        is_debug=YES
    fi
    shift
done

# add any parameters for debug run
if [ "$is_debug" != "YES" ]; then
    weblet_pid=`pgrep -x weblet-main`
    
    if [ -z "${weblet_pid}" ]; then
        echo "Start a new instance of weblet-main"
        socat UNIX-RECV:/tmp/weblet-socket EXEC:${local_path}/weblet-local/weblet-main 2> /tmp/weblet-log &
    fi
    
    # XXX: do polling for the socket to be ready
    while [ ! -S /tmp/weblet-socket ]; do sleep .5; done
    if [ "$is_daemon" != "YES" ]; then
        echo | socat STDIN UNIX-SENDTO:/tmp/weblet-socket
    fi
else 
    ${local_path}/weblet-local/weblet-main
fi

